name: Ubuntu make

on:
  push:
    branches: [ master, development, libov_win ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fetchtags
      run: git fetch --unshallow --tags
    - submodules:
      run: git submodule init && git submodule update
    - name: make
      run: make
