name: MacOS make

on:
  push:
    branches: [ master, development, libov_win ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch git tags
      run: git fetch --unshallow --tags
    - name: Install submodules
      run: git submodule init && git submodule update
    - name: Install Dependencies
      run: brew install pkgconfig libxml2 glibmm libxml++ jack liblo libsndfile gtkmm3 eigen boost gsl fftw libsamplerate cpprestsdk nlohmann-json openssl coreutils
    - name: Configure
      run: cmake .
    - name: Build
      run: make

