name: Windows make

on:
  push:
    branches: [ libov_win ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: pacman --noconfirm -Syu git make gcc pkg-config libxml++2.6 jack2 liblo libsndfile fftw gsl eigen gtkmm3 boost libltc xxd gtksourceviewmm webkit2gtk
    - name: fetchtags
      run: git fetch --unshallow --tags
    - name: submodules
      run: git submodule init && git submodule update
    - name: make
      run: make
